config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  def self.shared
    where(published: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable, 
         :validatable

  has_many :books

  validates :username, presence: true, length: { in: 5..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :check_the_user_ownership, only: [:edit, :update, :destroy]

  def index
    @books = current_user.books
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :pagecount, :published, :user_id)
    end

    def check_the_user_ownership
      if @book.user != current_user
        redirect_to books_url, notice: 'You are not allowed to perform this action!'
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @shared_books = Book.shared
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :pagecount %>
    <%= form.number_field :pagecount %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if @books.empty? %>
  <p>You have no books, yet.</p>
<% else %>
<h1>Your Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Pagecount</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.pagecount %></td>
        <td><%= book.published %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h1>Book Info</h1>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Pagecount:</strong>
  <%= @book.pagecount %>
</p>

<p>
  <strong>Published:</strong>
  <%= @book.published %>
</p>



<p>
  <% if @book.user != current_user %>
    <strong>User:</strong>
    <%= @book.user.username %>
  <% else %>
    This is one of your books.
  <% end %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSharingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Book Sharing App', root_path %></h1>
      <nav>
        <% if user_signed_in? %>
        <p>||
          <%= link_to 'Shared Books', root_path %> ||
          <%= link_to 'Your Books', books_path %> ||
          <%= link_to 'New Book', new_book_path %> ||
          Signed in as <%= current_user.username %> 
          (<%= current_user.email %>) ||
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %> ||
        </p>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path %> |
        <%= link_to 'Log in', new_user_session_path %>
      <% end %>  
      </nav>
    </header><hr>

    <p id="notice"><%= notice %></p>
    <div>
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/welcome/index.html.erb
<% if user_signed_in? and not @shared_books.empty? %>
<h1>Shared Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Pagecount</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <% @shared_books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td><%= book.pagecount %></td>
        <td><%= book.user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>Welcome to book sharing app. Happy sharing!</p>
<% end %>